### ISSUE TITLE
OpenSeries CHANGELOG v1.1.2 - v1.7.0

### ISSUE THREAD

**Issue by slowy07** [bellshade/OpenSeries#4]
CHANGELOG

## version: [v1.1.2](https://github.com/bellshade/OpenSeries/tree/v1.1.2)
- restructure folder ``example`` #6 
- function statistika
  - entropy #6 
  - standar deviasi #6 

## version: [v1.6.6](https://github.com/bellshade/OpenSeries/tree/v1.6.6)
- fisika:
  - fungsi ketinggian barometrik #20 
  - fungsi gaya sentripental #24 
  - fungsi efek doppler #24 
- matematika:
  - fungsi dari euler pi #22 
  - fungsi sigmoid 8b842ee
- dev patch
  - improvement dari website openseries #14 
    - embed replit #13 
    - fix responsive design landing page #12
    - dokumentasi
      - entropy
      - instalasi
  - improving custom error handling #23 , 8b842ee
  - menambah docstring #25
  - docker support #28 

## next version
- library:
  - matematika
    - distribusi binomial #36 
    - fungsi gaussian #49 
    - fungsi derivative #56
    - angka spesial #37 
      - angka armstrong #38
      - angka automorphic #42 
      - angka pronic #51 
      - angka segitiga #52 
- web:
  - fitur playground 46181e339ac0abec53ac160e408e6c356d424cbf
  - fitur darkmode #40 9321effbea5305c4c2fba2897cbd7f5e95e33284
- dev patch:
  - memisahkan branch web openseries ke repositori baru [e9ab6b4](https://github.com/bellshade/OpenSeriesWeb/commit/e9ab6b40113b802d61ab1e426816f6161b287fe7)
  - memperbaiki responsive navbar z-index [2c66be1 - OpenSeriesWeb](https://github.com/bellshade/OpenSeriesWeb/commit/2c66be19f7e7303c0e60d8a88a8b404f7c985866)
  - menambahkan konfigurasi pre-commit dan mergify di repositori web [12](https://github.com/bellshade/OpenSeriesWeb/pull/12)
  - merubah penamaan variabel konstan #33 
  - improvisasi kostum error handling #34 
  - improvisasi fungsi pada matematika #44 
  - menambahkan library 3rd untuk color ANSI code #44 
  - dokumentasi parameter commit ``CONTRIBUTING.md`` #53 
  - menambahkan badge #54 
  - minor navbar darkmode issue [#42 - OpenSeriesWeb](https://github.com/bellshade/OpenSeriesWeb/pull/42)

**Comment by slowy07** [comment]
untuk markdown gass di dokumentasi web @dherlyar , kalo yang lib nnti biar di cover, pullnya nnti markdownnya ke branch ``develop`` ya 💯

**Comment by dherlyar** [comment]
sudah menambahan docs entropy & standar deviasi

**Comment by slowy07** [comment]
CHANGELOG v1.1.2 - v1.7.0

close, masuk ek issue terbaru dari develop bellshade
