### ISSUE TITLE
Penambahan Icon Penggunaaan Code atau Bahasa, dan Bisa digunakan Tools Seperti Replit atau menggunakan Google Collabs

### ISSUE THREAD

**Issue by rafiqmyura** [bellshade/OpenSeries#45]
## Penambahan

- Tambahkan icon bahasa pemrograman dan tools kit
- Lebih baik juga tambah card contrib

## Screenshots atau contoh error

![image](https://github.com/bellshade/OpenSeries/assets/139538109/84024769-669c-4a14-9799-baa6f76e2c73)

```
pesan error
```

## Desktop (please complete the following information):

- OS: `linux/windows/macOS`
- Python: `version`

terima kasih

**Comment by slowy07** [comment]
@abnvlf

**Comment by slowy07** [comment]
gkada jalan di google colab @rafiqmyura , bisa play on web aja nanti, untuk selebihnya bisa menjadi masukan yang bagus 💯

**Comment by rafiqmyura** [comment]
yaudah, paling sih letakan aja support by tools gitu, dan untuk contribnya bikin 3 - 4 colum card, nama, foto, social media, dan role

**Comment by abnvlf** [comment]
Terimakasih sarannya, semuanya sudah masuk roadmap kami ya🫡✨

**Comment by rafiqmyura** [comment]
Sama Sama. Saya berusaha keras untuk memberikan kritik dan saran :D

**Comment by slowy07** [comment]
close, openseries sudah bisa dijalankan dari web
