### ISSUE TITLE
image not rendering

### ISSUE THREAD

**Issue by ahmadshiddiq** [bellshade/OpenSeries#63]
## Masalah

File tidak ditemukan di halaman tentang:
https://openseries.pages.dev/docs

## Screenshots atau contoh error

<img width="814" alt="image" src="https://github.com/bellshade/OpenSeries/assets/53107961/a7045cee-2ed3-4889-8ea6-7cdfde3d43fb">

**Comment by abnvlf** [comment]
thanksss!!! sudah diperbaiki, akan diupdate ke https://openseries.pages.dev/ di next patch!!
