### ISSUE TITLE
code in replit for documentation

### ISSUE THREAD

**Issue by rulanugrh** [bellshade/OpenSeries#7]
Matematika : 
- [Radian Ke Derajat](https://replit.com/@ItsArul/RadianKeDerajat)
- [Luas Lingkaran](https://replit.com/@ItsArul/LuasLingkaran)
- [Keliling Lingkaran](https://replit.com/@ItsArul/KelilingLingkaran)
- [Diameter Lingkaran](https://replit.com/@ItsArul/DiameterLingkaran)
- [Persamaan Kuadrat](https://replit.com/@ItsArul/PersamaanKuadrat)

Fisika : 
- [Kecepatan](https://replit.com/@ItsArul/Kecepatan)
- [Energi Kinetik](https://replit.com/@ItsArul/EnergiKinetik)
- [Masa Jenis](https://replit.com/@ItsArul/MasaJenis)
- [Energi Potensial](https://replit.com/@ItsArul/EnergiPotensial)
- [Hukum Ohm](https://replit.com/@ItsArul/HukumOhm)

Statistika: 
- [Entropy](https://replit.com/@ItsArul/Entropy)
- [Standar Deviasi](https://replit.com/@ItsArul/StandarDeviasi)

**Comment by rulanugrh** [comment]
@abnvlf update baru bang

**Comment by dherlyar** [comment]
@rulanugrh woke

**Comment by slowy07** [comment]
closed issue
